/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e4e2e3",
        "on-tertiary-container": "#a38c6a",
        "surface-container-high": "#eae7e9",
        "tertiary-container": "#35260c",
        "surface-tint": "#545f73",
        "outline-variant": "#c5c6cd",
        "error-container": "#ffdad6",
        "tertiary": "#1e1200",
        "surface-container-low": "#f5f3f4",
        "primary-fixed": "#d8e3fb",
        "on-surface": "#1b1b1d",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-container": "#8590a6",
        "on-background": "#1b1b1d",
        "surface-container": "#f0edef",
        "on-primary-fixed": "#111c2d",
        "on-tertiary-fixed": "#271902",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3c475a",
        "on-tertiary-fixed-variant": "#564427",
        "on-surface-variant": "#45474c",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed": "#fadfb8",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-container": "#1e293b",
        "inverse-surface": "#303032",
        "tertiary-fixed-dim": "#ddc39d",
        "primary": "#091426",
        "outline": "#75777d",
        "on-error-container": "#93000a",
        "on-secondary-container": "#54647a",
        "inverse-primary": "#bcc7de",
        "secondary": "#505f76",
        "background": "#fbf8fa",
        "surface": "#fbf8fa",
        "on-primary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "surface-dim": "#dcd9db",
        "surface-bright": "#fbf8fa",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f3f0f2",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed-dim": "#bcc7de",
        "surface-variant": "#e4e2e3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "sm": "8px",
        "container-max": "1440px",
        "xs": "4px",
        "lg": "24px",
        "gutter": "20px",
        "base": "4px",
        "xl": "32px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "data-mono": ["Inter"],
        "label-sm": ["Inter"],
        "h2": ["Inter"],
        "h3": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "data-mono": ["13px", {"lineHeight": "18px", "letterSpacing": "0", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h3": ["20px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600"}],
        "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
